import 'bootstrap/dist/css/bootstrap.min.css';
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "./global.css";
import StoreProvider from './StoreProvider';
import Navbar from './components/navbar/navbar';
import Footer from './components/footer/footer';
import CookieConsentOffcanvasBootstrap from './components/cookie-offcanvas/cookie-offcanvas';




export const metadata = {
  title: 'V-Real',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <StoreProvider>
        <Navbar />
            {children}
            <Footer />
          <CookieConsentOffcanvasBootstrap />
        </StoreProvider>
        </body>
    </html>
  );
}
